#!/bin/bash
#
# shared helper function for building genomic+MT DNA references + species identification index
#

# strict mode; any non-existing directory will crash
set -eu

# Required software (local) and (online) eutils suite;
# Eutils can be downloaded as stand-alone tools to, but for our use-case this serves the needs
eutils=https://eutils.ncbi.nlm.nih.gov/entrez/eutils
efetch=$eutils/efetch.fcgi
esearch=$eutils/esearch.fcgi
# remnands of manually installing executables within this repo
#fasterqdump=$(dirname $(readlink -f $0))/../../utils/fasterq-dump
#datasets=$(dirname $(readlink -f $0))/../../utils/datasets
fasterqdump=fasterq-dump
datasets=datasets
samtools=samtools
minimap2=minimap2
# TODO:
# install ~/toolkit/xlsx2csv.py
# install csvlook

REPODIR=$(dirname $(dirname $(dirname $(readlink -f $0))))
CONFIGFILE=$REPODIR/config/referencedata.yaml
REFERENCE_DATA_DIR=$(python3 -c "import yaml; print(yaml.safe_load(open('"$CONFIGFILE"'))['reference_data_dir'])")
# internally generated reference_assembly_data.tsv (by this pipeline)
input_tsv=$REFERENCE_DATA_DIR/reference_assembly_data.tsv

function validate_refdir() {
  # validate that the multi-reference directory is correct
  if [ $# -eq 0 ]; then
    echo "exit: required existing \$refdir (as 1th argument)"
    exit 1
  fi
  refdir=$1
  if [ -z "$refdir" ] || [ ! -d $refdir ]; then
    echo "exit: required existing \$refdir (as 1th argument)"
    exit 1;
  elif [ ! -f $refdir/accessions.txt ]; then
    echo "exit: expected file $refdir/accessions.txt"
    exit 1;
  elif [ ! -d $refdir/WGS ]; then
    echo "exit: expected subdirectory $refdir/WGS"
    exit 1;
  elif [ ! -d $refdir/SRR ]; then
    echo "exit: expected subdirectory $refdir/SRR"
    exit 1;
  elif [ ! -d $refdir/refs ]; then
    echo "exit: expected subdirectory $refdir/refs"
    exit 1;
  elif [ ! -d $refdir/mmidx ]; then
    echo "exit: expected subdirectory $refdir/mmidx"
    exit 1;
  elif [ ! -d $refdir/NUCCORE ]; then
    echo "exit: expected subdirectory $refdir/NUCCORE"
    exit 1;
  fi
  }

function validate_input_tsv() {
  # QC on input tsv file "reference_assembly_data.tsv" (generated by this pipeline)
  # Cowardly refuse to do anything once TSV format has changed
  input_tsv=$1
  header="reference,taxid,MT_num,MT_assembly,MT_accession,MT_length,MT_source",fasta
  if [ ! -f $input_tsv ]; then
    echo "error: no such file: $input_tsv"
    exit 1
  elif [ "$(head -n1 $input_tsv | tr "\t" ",")" != "$header" ]; then
    echo "error: output format of $input_tsv does not confirm to '$header'"
    exit 1
  fi
}

function generate_reference_accession_dataset_UID() {
  # convert all accessions (genomic+MT) stored in ***-references.tsv into the md5hash of its comma-separated string
  input_tsv=$1
  # below two bash statements are identical, but csvlook/csvcut is not installed on vanilla UNIX systems
  #csvcut -t -c reference,MT_accession $input_tsv | sed 1d | sort -k1,1 -t',' | \
  cut -f 1,5 $input_tsv | sed 1d | sort -k1,1  | tr "\t" "," | \
    tr "\n" "," | sed 's/,,/,/g' | sed 's/,$//' \
    | md5sum | awk '{ print $1 }'
}


function convert_tsv_to_nested_reference_array() {
  # convert ***-references.tsv into a nested array of ( WGS accession, MT accession, reference.fa ) file
  #
  # In scripts implementing this, use this syntax:
  # declare -a reference_array=()
  # convert_tsv_to_nested_reference_array $input_tsv reference_array
  # for ((i=0; i<${#reference_array[@]}; i+=5)); do
  #   read -r WGS_accession MT_accession MT_assembly MT_source ref_fasta <<< "${reference_array[@]:i:5}"
  #   your logic here ...
  # done
  local input_tsv=$1
  local -n ref_array=$2
  local_outdir=$(dirname $(readlink -f $input_tsv))/refs
  while IFS=":" read -r reference taxid MT_num MT_assembly MT_accession MT_length MT_source fasta;
  do
    WGS_accession=$reference
    MT_accession="${MT_accession:-NA}"
    MT_source="${MT_source:-NA}"
    MT_assembly="${MT_assembly:-NA}"
    if [ "$MT_source" == "external" ]; then
      outfa=$local_outdir/$WGS_accession"__external__"$MT_accession.fa
    elif [ "$MT_source" == "provided" ]; then
      outfa=$local_outdir/$WGS_accession"__provided__"$MT_accession.fa
    elif [ "$MT_source" == "included" ]; then
      outfa=$local_outdir/$WGS_accession"__included__"$MT_accession.fa
    elif [ "$MT_source" == "NA" ]; then
      outfa=$local_outdir/$WGS_accession"__nd__nd".fa
    elif [ -z $MT_source ]; then
      outfa=$local_outdir/$WGS_accession"__nd__nd".fa
    else
      echo "error: NotImplementedError(MT_source=$MT_source)"
      exit 1
    fi
    # (superfluous) check if fasta nameing (in generate_reference_assembly_dataframe.py)
    # hasn't changes meanwhile.
    if [ "$(basename $outfa)" != "$fasta" ]; then
      echo "error: NotImplementedError($outfa!=$fasta)"
    fi
    # increment ref_array
    ref_array+=("$WGS_accession" "$MT_accession" "$MT_assembly" "$MT_source" "$outfa")
  done < <(cat $input_tsv | tr "\t" ":" | sed 1d | sort -k1,1 -t':')
  }
