# Python Imports
import os

# variables
DATADIRNAME: str = ""
CONFIGDIRNAME: str = ""

# internal variables/shortcuts
_ospdn = os.path.dirname
_ospjn = os.path.join

# get DATADIRNAME & CONFIGDIRNAME, dependent on how this repo is made accessible
datadirname_options: dict[str, str] = {
    "repo-itself": _ospjn(_ospdn(_ospdn(__file__)),"data"),
    "installed": _ospjn(_ospdn(__file__), "data"),
}
for option in datadirname_options.values():
    if os.path.isdir(option):
        DATADIRNAME = option
        CONFIGDIRNAME = _ospjn(_ospdn(option),"config")
        break
else:
    msg = "can't locate /data directory in package [%s]" % __file__
    raise FileNotFoundError(msg)

# primary, single-source-of-thruth input, copied from xlsx file, being the required input
SPECIES_REFERENCE_TSV = os.path.join(DATADIRNAME,"supported-reference-species.tsv")
# reformatted representation of SPECIES_REFERENCE_TSV, generated by apollo-reference
ASSEMBLY_REFERENCE_TSV = os.path.join(DATADIRNAME,"reference_assembly_data.tsv")
# generated by apollo-reference
FASTQ_REFERENCE_TSV = os.path.join(DATADIRNAME,"accession2SRR.tsv")
# yaml that exposes where actual multi-reference data is located
REFERENCEDATA_YAML = os.path.join(CONFIGDIRNAME,"referencedata.yaml")