#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Path to the symlinked engine
ENGINE="./ci-tools/node_modules/.bin/commitlint"
CONFIG="./ci-tools/config/commitlint.config.js"

if [ -f "$ENGINE" ]; then
  node "$ENGINE" --config "$CONFIG" --edit "$1"
else
  echo "# Error: commitlint not found. Did you run 'npm install' in master-ci-templates?"
  exit 1
fi
